### PR TITLE
Configuration for automated docker image and service update process

### PR DESCRIPTION
**Pull request by MindMaster98**
# Motivation

This pull request enables an automated update process for the Qanary pipeline. All images will be build automatically and pushed to Docker Hub. Although, there is a pipeline running on a demo server, which will be updated with each commit to the master branch. To finish the configuration it is necessary that a maintainer adds the following secrets to the repository.

# Needed Configuration

- [x] Stop currently used demo instance of the Qanary Pipeline
- [x] Providing all repository secrets:
  - [x] DOCKER_USER := username of the Docker Hub account maintaining the Qanary components images
  - [x] DOCKER_PASSWORD := access token for the Docker Hub account
  - [x] API_KEY := API key used by the [microservice updater](https://github.com/MindMaster98/microservice-updater)
  - [x] UPDATER_HOST := https://demos.swe.htwk-leipzig.de:40195/

### CODE REVIEW

**Comment by Perevalov** [comment]
The secrets were set. I will stop the currently running instance a little bit later

**Comment by Perevalov** [comment]
I stopped the instance at port `40111` and will merge it now

**Comment by Perevalov** [comment]
@MindMaster98 The run failed, could you check: https://github.com/WDAqua/Qanary/runs/7540263874 ?

**Comment by MindMaster98** [comment]
> @MindMaster98 The run failed, could you check: https://github.com/WDAqua/Qanary/runs/7540263874 ?

I checked the action. The permissions of the script building the docker images weren't set correctly. I updated the file and created a new Pull Request (https://github.com/WDAqua/Qanary/pull/96). Although I run the action on my forked repository and there it works now (https://github.com/MindMaster98/Qanary/runs/7540878020?check_suite_focus=true).

**Pull request merged**
