### PR TITLE
Update docker-deployment.yml

### PR DESCRIPTION
**Pull request by dschiese**
@anbo-de 
The deployment action still used the stardog env variable. Changed it with respect to your changes in https://github.com/WDAqua/Qanary/commit/0a810e29e140f2d9b189192be93dd7179b6cba5a 

Hopefully everything is configured now

### CODE REVIEW

**Comment by dschiese** [comment]
The Maven action failed somehow? Any suggestions?

**Comment by dschiese** [comment]
@anbo-de Can be merged

**Comment by dschiese** [comment]
It stills fails somehow. The build ends successfully and within the build-process no errors occur?

**Comment by anbo-de** [comment]
> It stills fails somehow. The build ends successfully and within the build-process no errors occur?

The reason was a process that does not return the code `0`. 

The `set -e` command that every command completed successfully, but, the error message is not visible. I removed it: https://github.com/WDAqua/Qanary/commit/ade52eee333b691f2ff03eb6c50d1c9c92764045

Works now: https://github.com/WDAqua/Qanary/actions/runs/7175970943 :smile:

**Pull request merged**
