### PR TITLE
Added query to insert required triples on graph init.

### PR DESCRIPTION
**Pull request by dschiese**
v3.14.0

- added an INSERT SPARQL query which contains required triples

### CODE REVIEW

**Comment by anbo-de** [comment]
@dschiese Looks nice. Thank you.

**Comment by anbo-de** [comment]
@dschiese There is a problem during the Maven build, see https://github.com/WDAqua/Qanary/actions/runs/9464144836/job/26070830092#step:4:39720 and please fix it.

**Comment by dschiese** [comment]
New PR: https://github.com/WDAqua/Qanary/pull/280

@anbo-de I've added an action to execute `mvn test` on PR's as this wasn't done before. With the latest [check](https://github.com/WDAqua/Qanary/actions/runs/9478322875/job/26114532028?pr=280), some more errors occurred.

**Comment by dschiese** [comment]
> New PR: #280
> 
> @anbo-de I've added an action to execute `mvn test` on PR's as this wasn't done before. With the latest [check](https://github.com/WDAqua/Qanary/actions/runs/9478322875/job/26114532028?pr=280), some more errors occurred.

Is the dependency 
```
        <dependency>
            <groupId>eu.wdaqua.qanary</groupId>
            <artifactId>qald.evaluator</artifactId>
            <version>[1.0.2,2.0.0)</version>
        </dependency>
```
necessary for the qanary_pipeline-template artifact? I am asking as this dependency causes the current existing errors. 

If not, we could easily remove it and the tests run successfully.

**Pull request merged**
